#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket daemon"

        start-stop-daemon \
            --start \
            --background \
            --make-pidfile \
            --pidfile /var/run/aesdsocket.pid \
            --exec /usr/bin/aesdsocket \
            -- -d
        ;;

    stop)
        echo "Stopping aesdsocket daemon"

        start-stop-daemon \
            --stop \
            --pidfile /var/run/aesdsocket.pid \
            --signal SIGTERM
        ;;

    restart)
        $0 stop
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
